openapi: 3.0.1
info:
  title: Event Cadence Webhook API
  description: ""
  version: 1.0.3
servers:
- url: https://webhookconnect.eventcadence.com/connect
  description: Production
- url: https://cheetahconnect.eventcadence.com/connect
  description: Production (Cheetah)
tags:
- name: registerattendee
paths:
  /{eventCode}/registerattendee:
    post:
      tags:
      - registerattendee
      summary: Register an Attendee
      description: Use this to register attendees to your event. You'll need both
        an `eventCode` and a `key` which you can get from your Cadence contact for
        your event.
      operationId: registerattendee
      parameters:
      - name: eventCode
        in: path
        description: The webhook eventCode provided to you by your contact at Cadence.
        required: true
        schema:
          type: string
      requestBody:
        description: JSON body of fields used to register the attendee.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/registerattendee'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        400:
          description: required field missing
          content: {}
        404:
          description: eventCode not found
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    registerattendee:
      required:
      - key
      type: object
      properties:
        key:
          type: string
        profile:
          type: object
          properties:
            prefix:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            phone:
              type: string
            website:
              type: string
            facebook:
              type: string
            twitter:
              type: string
            linkedin:
              type: string
            instagram:
              type: string
            thirdPartyId:
              type: string
            title:
              type: string
            department:
              type: string
            company:
              type: string
            city:
              type: string
            state:
              type: string
            country:
              type: string
            assistantName:
              type: string
            assistantPhone:
              type: string
            assistantEmail:
              type: string
            motto:
              type: string
            biography:
              type: string
            customFields:
              type: array
              example:
              - fieldName: Favorite color
                fieldValue: Blue
              - fieldName: Alumni year
                fieldValue: "1998"
              items:
                $ref: '#/components/schemas/customFields'
        eventInfo:
          type: object
          properties:
            groups:
              type: object
              properties:
                groupNames:
                  type: array
                  example:
                  - Group A
                  - Group B
                  - Group C
                  items:
                    type: string
    customFields:
      type: object
      properties:
        fieldName:
          type: string
        fieldValue:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
